### ISSUE TITLE
网站的翻译不准确

### ISSUE THREAD

**Issue by chenyuntc** [apachecn/pytorch-doc-zh#142]
http://pytorch.apachecn.org 上的 
>PyTorch 是第一个进入 Python 版本的深度学习框架.
我们正在进行早期版本的测试. 期待一些商业投资.

我觉得
> Expect some adventures.

意思是PyTorch还有些Bug，使用PyTorch就像冒险一样会遇到一些挑战。不是` 期待一些商业投资.` :joy:

**Comment by wangyangting** [comment]
2333333333333 还考虑了半天, 还以为是前期刚开始, 需要人投资支持好搞事情呢！~  
那 Expect some adventures 这句英文怎么翻译看着更好更舒服一点点呢, 期待一些冒险, 期待一些挑战, 还是 。。。 - - 、

**Comment by chenyuntc** [comment]
> 我们还处于早期的阶段， 准备迎接奇遇

唉 我英语无力啊 :sweat:

**Comment by wangyangting** [comment]
> 我们正处于早期版本的测试阶段. 准备迎接奇遇.

遵循大佬的建议，修改成这样了，英语无力啊 - - 、、、

**Comment by chenyuntc** [comment]
加油   :clap:  :+1:
