### ISSUE TITLE
可否在遵守 GNU General Public License v3.0 的情况下，修改，重新发布这个项目内容呢？

### ISSUE THREAD

**Issue by fendouai** [apachecn/pytorch-doc-zh#167]
GNU General Public License v3.0

**Comment by jiangzhonglian** [comment]
???

**Comment by fendouai** [comment]
基于这个内容，继续修改或者直接发布到网站上？

**Comment by jiangzhonglian** [comment]
那小哥哥觉得应该怎么操作才对呢？？  
我没太懂你的意思

**Comment by fendouai** [comment]
大佬，就是我想基于这个内容， build 个文档放在我的网站上可以不？咨询一下版权问题。

**Comment by jiangzhonglian** [comment]
小哥哥，这个是可以的，请标明：信息的来源和作者

后期如果有兴趣，可以相互了解一下，说不定有合作的机会。

**Comment by fendouai** [comment]
好的，会注明来源和作者。

**Comment by jiangzhonglian** [comment]
我查了查  GFDL 是一个不错的协议，我呆会加一下协议！
