### ISSUE TITLE
概率分布的文档翻译得难以阅读了

### ISSUE THREAD

**Issue by the0demiurge** [apachecn/pytorch-doc-zh#208]
http://pytorch.apachecn.org/cn/0.3.0/distributions.html

![image](https://user-images.githubusercontent.com/11363529/38684293-efef108c-3ea1-11e8-8ff0-d1db0bfff49a.png)

“使用 *是是*梯度下降法”

**Comment by the0demiurge** [comment]
```rst
Policy gradient methods can be implemented using the
:meth:`~torch.distributions.Distribution.log_prob` method, when the probability
density
```
英文原文这里是meth，到了中文里变成了math，我不太了解rst，手头没有好用的工具，不太清楚是不是由于这个引起的一连串解析错误😅

**Comment by jiangzhonglian** [comment]
应该是他写错了吧，， 其他的公式英文都应该是 math , 这个是官网的比如吧。
不信你搜索一下：meth 有多少

**Comment by wizardforcel** [comment]
@jiangzhonglian 已经校验过了，你重新编译一下

**Comment by bringtree** [comment]
@wizardforcel 飞龙大佬 这种 能不能 有些自动化工具 自动编译的？

**Comment by wizardforcel** [comment]
@bringtree 问片刻，我不管编译和部署。。。

**Comment by the0demiurge** [comment]
可以弄一个hooks检测到某分支改变就自动部署之类的吧。。

**Comment by wizardforcel** [comment]
TravisCI
