### ISSUE TITLE
连接失效 multi-GPU examples

### ISSUE THREAD

**Issue by bringtree** [apachecn/pytorch-doc-zh#230]
http://pytorch.apachecn.org/cn/tutorials/beginner/former_torchies/parallelism_tutorial.html#id5
![image](https://user-images.githubusercontent.com/20106478/38885263-00617232-42a5-11e8-823a-e7deb27be631.png)
对比了下和原英文文档  是一样的 但是原来英文文档没有失效

**Comment by wizardforcel** [comment]
格式已修改，请重新编译看看行不行

**Comment by jiangzhonglian** [comment]
小哥哥， 格式检验如果没问题，社区留言：翻译和校验后，页面格式和原文一致，无错乱！

**Comment by jiangzhonglian** [comment]
每周一编译一次，这个就是确认问题和修改，可以先休息休息

**Comment by bringtree** [comment]
![image](https://user-images.githubusercontent.com/20106478/38911927-0f38f626-4305-11e8-8e93-b5a49e3923ed.png)
