### ISSUE TITLE
dcgan_faces_tutorial.md 中的最后还有下面几行，我始终push不上去，谁帮忙给加上。谢谢。

### ISSUE THREAD

**Issue by wangshuai9517** [apachecn/pytorch-doc-zh#339]
**代码总运行时间:** ( 28 分钟 51.332 秒)

[`下载Python源代码: dcgan_faces_tutorial.py`](../_downloads/dc0e6f475c6735eb8d233374f8f462eb/dcgan_faces_tutorial.py)

[`下载Jupyter笔记: dcgan_faces_tutorial.ipynb`](../_downloads/e9c8374ecc202120dc94db26bf08a00f/dcgan_faces_tutorial.ipynb)

[Gallery generated by Sphinx-Gallery](https://sphinx-gallery.readthedocs.io)

**Comment by wangshuai9517** [comment]
**代码总运行时间:** ( 28 分钟 51.332 秒)

[`下载Python源代码: dcgan_faces_tutorial.py`]
  (../_downloads/dc0e6f475c6735eb8d233374f8f462eb/dcgan_faces_tutorial.py)

[`下载Jupyter笔记: dcgan_faces_tutorial.ipynb`] 
 (../_downloads/e9c8374ecc202120dc94db26bf08a00f/dcgan_faces_tutorial.ipynb)

[Gallery generated by Sphinx-Gallery]  (https://sphinx-gallery.readthedocs.io)

**Comment by wizardforcel** [comment]
这个一律删掉
