### ISSUE TITLE
翻译质量

### ISSUE THREAD

**Issue by SsnL** [apachecn/pytorch-doc-zh#344]
你们好，我是pytorch team的core dev，很激动看到你们在翻译pytorch的doc。我看了一些翻译的文档，对于翻译质量有所担忧。比方 [cuda semantics](https://github.com/apachecn/pytorch-doc-zh/blob/master/docs/1.0/notes_cuda.md)中很多语句并不通顺，有种机翻+小修改的感觉。例如：

> 释放所有 unused 的缓存内存

> 但是，分配器管理的未使用内存仍将显示为使用 nvidia-smi

> 如果你想创建一个与另一个 tensor 相同类型和大小的 tensor，并用一个或零填充它

> 使用 nn.DataParallel 而不是多处理

所以想请咨询一下，你们有没有计划进行额外的审核和update。

再次感谢你们的付出。

**Comment by jiangzhonglian** [comment]
你好，感谢你的建议：
翻译是第一个阶段：一般是机翻+小修改。（翻译不是一蹴而就）
校验还有几个阶段，一般是我们在使用的过程中会进行迭代优化，不是一次性完成的。
不然效率太慢了，还会影响后面的校验。

-- 一般我们弄完一个版本，至少有2～4遍校验的过程。

**Comment by SsnL** [comment]
好的，谢谢解释。祝顺利！

**Comment by wizardforcel** [comment]
我们有这个计划。

不过这个翻译活动从1月20开始，到现在也就两个月。时间太短了，连一轮翻译都没有结束，你可以看到很多章节还是空的。

另外作为组织者，我们只能尽可能加大宣传力度。内容给不给力还要看大家啊。😂😂
