### ISSUE TITLE
请问两个loss相加如何backward?

### ISSUE THREAD

**Issue by charlesfufu** [apachecn/pytorch-doc-zh#349]
![image](https://user-images.githubusercontent.com/33311822/56749498-6c48df00-67b4-11e9-8f36-1d385d246d9c.png)
![image](https://user-images.githubusercontent.com/33311822/56749520-779c0a80-67b4-11e9-9567-a575c5100e06.png)
求教这个报错的原因是什么？

**Comment by lartpang** [comment]
这说的是只能在训练模式反向传播，你是改成了测试模式么？
