### ISSUE TITLE
【无需编译】如何下载到本地查看页面内容？

### ISSUE THREAD

**Issue by Tao-Zhou** [apachecn/pytorch-doc-zh#352]

**Comment by jiangzhonglian** [comment]
@wizardforcel  龙哥，这个方便实现吗？

**Comment by wizardforcel** [comment]
在有 summary 地方执行 gitbook pdf

**Comment by Ir1d** [comment]
用 ci 生成 pdf 放仓库里如何

**Comment by jiangzhonglian** [comment]
如果方便实现的话，最好自动化都生成好就最好了，方便大家学习和下载。
由于CI是龙哥原来负责的，所以这个主要看龙哥的建议 @wizardforcel

**Comment by jiangzhonglian** [comment]
这个是有gitbook 弄得，所以通过gitbook 的命令就可以，百度一下就行

**Comment by songmeixu** [comment]
用gitbook 折腾了半天，各种坑，最后也只是勉强产生了，但是代码部分超长的话，不像网页版会有滑动框， 至此我彻底放弃了，gitbook 已经失去官方维护，变成了收费服务，我想它也可以被开源社区抛弃了。如果有人能编译出正常的 pdf文档，请在这里通知我一下，多谢！

**Comment by jiangzhonglian** [comment]
这是编译完的页面： 
https://github.com/apachecn/pytorch-doc-zh/tree/gh-pages

你直接下载放到那个汤姆猫的服务器下面，就可以直接访问了。
