### ISSUE TITLE
添加 edit-on-github 插件  | 编辑页面跳转出错？修复

### ISSUE THREAD

**Issue by Ir1d** [apachecn/pytorch-doc-zh#355]
地址：https://github.com/njleonzhang/docsify-edit-on-github
场景：看到页面上有问题之后，repo 里的对应文件可能不太好找= =

**Comment by jiangzhonglian** [comment]
编辑页面，无法正常调整错误

主要是分为4个项目来编译，所以下周有空，我把代码修改修改在优化一下此功能
