### ISSUE TITLE
PyTorch 1.0 中文文档 & 教程 · Pytorch 中文文档

### ISSUE THREAD

**Issue by jiangzhonglian** [apachecn/pytorch-doc-zh#370]
https://pytorch.apachecn.org/docs/1.0/

**Comment by ShiLongCheng** [comment]
感谢这么多技术人员的贡献。

**Comment by jiangzhonglian** [comment]
> @ShiLongCheng
> 感谢这么多技术人员的贡献。

哈哈，人嘛：活着就是要开心、又要装逼才行！

**Comment by EOminghuanhuan8** [comment]
嗯，怎么怎么点都进不去文档呢就在这几个网页之间跳来跳去

**Comment by jiangzhonglian** [comment]
没有啊

**Comment by luvvien** [comment]
[感谢大佬们的分享](https://viencoding.com)

**Comment by xjtu-blacksmith** [comment]
> @EOminghuanhuan8
> 嗯，怎么怎么点都进不去文档呢就在这几个网页之间跳来跳去

Gitbook 的页面跳转好像一直不太行，不知道是不是因为在国内的原因

**Comment by jiangzhonglian** [comment]
额，我这边使用非常正常，你要不试试手机网络先？

**Comment by xjtu-blacksmith** [comment]
> @jiangzhonglian
> 额，我这边使用非常正常，你要不试试手机网络先？

现在没有什么问题，就是之前在其他一些用 GitBook 驱动的文档网站上会有跳转的问题

**Comment by smartleizi** [comment]
> @jiangzhonglian
> > @ShiLongCheng
> > 感谢这么多技术人员的贡献。
> 
> 哈哈，人嘛：活着就是要开心、又要装逼才行！

第一次这么不反感装逼的人！！！

**Comment by booxood** [comment]
棒棒棒

**Comment by michaelguan** [comment]
>very good

**Comment by Haizhuolaojisite** [comment]
看了这么多教程，真的手痒痒，好想做点项目

**Comment by jiangzhonglian** [comment]
> 看了这么多教程，真的手痒痒，好想做点项目

那还犹豫什么？上去就是干！
