### ISSUE TITLE
Pytorch 1.4 宣传认领

### ISSUE THREAD

**Issue by wizardforcel** [apachecn/pytorch-doc-zh#372]
注意：

1.  部分站点有每天的数量限制，请大家合理安排。
2.  请全文转载，文章开头附上这个仓库中原文的链接。

| 站点 | 贡献者 | 进度 |
| --- | --- | --- |
| [CSDN](https://www.baidu.com/s?wd=pytorch%20%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%A3%20site%3Ablog.csdn.net) | @wizardforcel | 100% |
| [博客园](https://www.baidu.com/s?wd=pytorch%20%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%A3%20site%3Acnblogs.com) | @wizardforcel | 100% |
| OSChina |  |  |
| SegmentFault |  |  |
| 掘金 |  |  |
| 简书 | @zhangqizky |  |
| 搜狐号 |  |  |
| 百家号 | @zhangqizky |  |
| 知乎专栏 | @fonttian |  |

> 留言格式

```
+   CSDN：@wizardforcel [链接](https://www.baidu.com/s?wd=pytorch%20%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%A3%20site%3Ablog.csdn.net)
+   博客园：@wizardforcel [链接](https://www.baidu.com/s?wd=pytorch%20%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%A3%20site%3Acnblogs.com)
```

**Comment by FontTian** [comment]
先提前认领一下知乎的教程部分,会在这几天陆续转发。

**Comment by zhangqizky** [comment]
百家号:@zhangqizky
简书:@zhangqizky

**Comment by zhangqizky** [comment]
百家号:@zhangqizky [链接](https://mbd.baidu.com/newspage/data/landingshare?pageType=1&isBdboxFrom=1&context=%7B%22nid%22%3A%22news_9606340307541646619%22%2C%22sourceFrom%22%3A%22bjh%22%7D)
