### ISSUE TITLE
广播语义中的代码写错了

### ISSUE THREAD

**Issue by Ein027** [apachecn/pytorch-doc-zh#380]
>
>#can line up trailing dimensions to make reading easier
>x=torch.empty(5,1,4,1)
>y=torch.empty(  3,1,1)
>(x+y).size()
torch.Size([5, 3, 4, 1])
>

这是无法广播的，其中第一行的维度应该是x=torch.empty(5,3,4,1)，参考官方文档：https://pytorch.org/docs/stable/notes/broadcasting.html

**Comment by Ein027** [comment]
> > 
> 
> # can line up trailing dimensions to make reading easier
> x=torch.empty(5,1,4,1)
> y=torch.empty( 3,1,1)
> (x+y).size()
> torch.Size([5, 3, 4, 1])
> 
> > 
> 
> 这是无法广播的，其中第一行的维度应该是x=torch.empty(5,3,4,1)，参考官方文档：https://pytorch.org/docs/stable/notes/broadcasting.html

**Comment by wizardforcel** [comment]
可以广播啊

首先右对齐

```
x: 5, 1, 4, 1
y: 1, 3, 1, 1
```

然后扩展值为 1 的维度：

```
x: 5, 3, 4, 1
y: 5, 3, 4, 1
```

**Comment by Ein027** [comment]
哦抱歉，是可以，要对两个都广播。
谢谢！


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: 飞龙 <notifications@github.com>
发送时间: 2019年7月10日 16:28
收件人: apachecn/pytorch-doc-zh <pytorch-doc-zh@noreply.github.com>
抄送: Ein027 <847234497@qq.com>, Author <author@noreply.github.com>
主题: 回复：[apachecn/pytorch-doc-zh] 广播语义中的代码写错了 (#380)




可以广播啊
 
首先右对齐
 x: 5, 1, 4, 1 y: 1, 3, 1, 1  
然后扩展值为 1 的维度：
 x: 5, 3, 4, 1 y: 5, 3, 4, 1
