### ISSUE TITLE
公式显示异常

### ISSUE THREAD

**Issue by Aefile** [apachecn/pytorch-doc-zh#381]
https://pytorch.apachecn.org/docs/1.0/blitz_autograd_tutorial.html
这个页面部分公式显示不出来

**Comment by Ir1d** [comment]
![image](https://user-images.githubusercontent.com/10709657/60968561-f7ffef80-a34f-11e9-9057-59ce42687f4b.png)
@jiangzhonglian @wizardforcel 刷新的时候会显示说没开评论

**Comment by jiangzhonglian** [comment]
OK ，我这边正在处理

**Comment by jiangzhonglian** [comment]
谢谢小哥的issues， 公式问题解决了

![image](https://user-images.githubusercontent.com/9199175/61028946-8d50c180-a3ec-11e9-9fa2-d76c4d63e87e.png)
