### ISSUE TITLE
Autograd：自动求导 · Pytorch 中文文档

### ISSUE THREAD

**Issue by jiangzhonglian** [apachecn/pytorch-doc-zh#382]
https://pytorch.apachecn.org/docs/1.0/blitz_autograd_tutorial.html

**Comment by shirubei** [comment]
感谢您的翻译。刚看了一下，雅可比矩阵的第一行最后一个元素以及最后一行第一个元素下标写错了，这2个应该互换一下才对。

**Comment by jiangzhonglian** [comment]
小哥哥，你看看是否方便提交一下PR？
