### ISSUE TITLE
blitz_cifar10_tutorial.md精度问题

### ISSUE THREAD

**Issue by my-hello-world** [apachecn/pytorch-doc-zh#383]
你好，感谢辛苦付出。
想请问下，训练结束后是不是需要保存模型，再加载它用来训练呢？
我按照教程的话，直接训练，训完测试，精度就一直是30%左右，也就是“盲猜“。
我改了一下，还是不行哎。我这样改的：
```
    # 读取之前保存的网络模型参数
    checkpoint = torch.load("./outputs/weights/3.pth")
    net.load_state_dict(checkpoint)
    # 使用测试数据测试网络  检查网络是否学到了一些东西。
    test(net)
```
希望解惑

**Comment by wizardforcel** [comment]
精度 50% 的话是盲猜，30% 的话你可以看看标签是不是有问题。。。

**Comment by my-hello-world** [comment]
@wizardforcel 

-  十类的话 盲猜是1/3不？

- 我需要先保存模型再加载过来测试吗
` torch.save(net.state_dict(), "./outputs/weights/{}.pth".format(epoch))`

-我看教程训练完直接测试了， 还是说它内部直接加载训练的最终模型吗？
