### ISSUE TITLE
冒号为中文符号

### ISSUE THREAD

**Issue by ChekeLee** [apachecn/pytorch-doc-zh#405]
https://pytorch.apachecn.org/docs/1.0/blitz_data_parallel_tutorial.html

在
设备（Device）：

device = torch.device("**cuda：0**" if torch.cuda.is_available() else "cpu")

这里cuda后面的冒号错用为中文冒号

**Comment by jiangzhonglian** [comment]
谢谢小哥哥， 已修正： https://github.com/apachecn/pytorch-doc-zh/pull/412
