### ISSUE TITLE
在C++中加载PYTORCH模型遇到问题

### ISSUE THREAD

**Issue by laomaup** [apachecn/pytorch-doc-zh#433]
您好，谢谢您的分享，在在C++中加载PYTORCH模型遇到问题:
error: conversion from ‘torch::jit::script::Module’ to non-scalar type ‘std::shared_ptr<torch::jit::script::Module>’ requested
std::shared_ptr<torch::jit::script::Module> module = torch::jit::load("/data/dgxshare/laoma/pt/vest_mode/xx.pt")
是不是因为头文件没有找到的原因，还没解决。

**Comment by jiangzhonglian** [comment]
bug的问题，你最好开始百度/Google或者去相关技术群讨论。
