### ISSUE TITLE
聊天机器人教程 缺少代码

### ISSUE THREAD

**Issue by YiweiJiang2015** [apachecn/pytorch-doc-zh#458]
函数normalizeString的定义丢失，可以补上吗？
def normalizeString(s):
    s = unicodeToAscii(s.lower().strip())
    s = re.sub(r"([.!?])", r" \1", s)
    s = re.sub(r"[^a-zA-Z.!?]+", r" ", s)
    s = re.sub(r"\s+", r" ", s).strip()
    return s

**Comment by jiangzhonglian** [comment]
欢迎提交PR
