### ISSUE TITLE
使用TensorBoard进行可视化

### ISSUE THREAD

**Issue by Ryan-Lily** [apachecn/pytorch-doc-zh#475]
希望能在中文版本中添加使用TensorBoard进行可视化的教程。谢谢！

**Comment by jiangzhonglian** [comment]
使用 TensorBoard 可视化模型，数据和训练

https://pytorch.apachecn.org/docs/1.2/intermediate/tensorboard_tutorial.html

**Comment by Ryan-Lily** [comment]
非常感谢！
