### ISSUE TITLE
v1.4 使用 PyTorch 进行深度学习：60 分钟的闪电战文档连接不存在

### ISSUE THREAD

**Issue by EliotCao** [apachecn/pytorch-doc-zh#497]
[文档](https://pytorch.apachecn.org/docs/1.4/4.html)中“什么是 PyTorch？”、"Autograd：自动分化"、“神经网络”、“训练分类器"、“可选：数据并行”均找不到对应文档

**Comment by jiangzhonglian** [comment]
使用的是1.2版本的翻译，不是最新的，可能有一些API改动，以英文1.4为准

![image](https://user-images.githubusercontent.com/9199175/77289654-55d53b80-6d15-11ea-9845-78e1961856b3.png)
