### ISSUE TITLE
关于在线文档访问速度慢的问题

### ISSUE THREAD

**Issue by CatNofishing** [apachecn/pytorch-doc-zh#514]
在线文档访问速度太慢，必须得挂vpn才能流畅阅读，非常影响阅读体验，可否提供离线pdf版本或者其他离线下载链接，git克隆也非常慢，希望可以改进

**Comment by jiangzhonglian** [comment]
谢谢你的建议，网址已经授权，大家可以自由转载发布

网址的所有页面: 
https://github.com/apachecn/pytorch-doc-zh/tree/gh-pages

**Comment by jiangzhonglian** [comment]
> 组织构建[网站]

GitHub Pages(国外): https://pytorch.apachecn.org
Gitee Pages(国内): https://apachecn.gitee.io/pytorch-doc-zh

> 第三方站长[网站]

pytorch 中文文档: https://www.bookstack.cn/search/result?wd=pytorch
地址A: xxx (欢迎留言，我们完善补充)
