### ISSUE TITLE
文档内容错误

### ISSUE THREAD

**Issue by stormDL** [apachecn/pytorch-doc-zh#515]
在[这个章节](https://pytorch.apachecn.org/docs/1.2/beginner/blitz/neural_networks_tutorial.html)出现了如下错误：
![image](https://user-images.githubusercontent.com/23137138/83961578-16a39900-a8c7-11ea-8086-80974ba59b24.png)

**Comment by FontTian** [comment]
请描绘具体的错误.

**Comment by OreoGuo** [comment]
> 请描绘具体的错误.

MNIST数据集图片大小为28x28
