### ISSUE TITLE
pytorch.apachecn.org找不到ip

### ISSUE THREAD

**Issue by JonXia** [apachecn/pytorch-doc-zh#525]

**Comment by jiangzhonglian** [comment]
卧槽，工信部太牛逼了！ 目前GitHub部署的网站都无法访问量！

**Comment by jiangzhonglian** [comment]
卧槽。工信部太牛逼了，GitHub部署的网站都看不了了！

**Comment by Jiuyong** [comment]
我们当地电信网络显示是：

未连接：有潜在的安全问题

Firefox 检测到潜在的安全威胁，并因 pytorch.apachecn.org 要求安全连接而没有继续。

您可以做什么？

pytorch.apachecn.org 启用了被称为 HTTP 严格传输安全（HSTS）的安全策略，这意味着 Firefox 只能安全地与其连接。您无法添加例外以访问此站点。

这个问题大多与网站有关，无法通过您的操作解决。您可以向此网站的管理者反馈此问题。

详细了解…

这个到底是什么造成的？

**Comment by Jiuyong** [comment]
> 
> 
> 卧槽。工信部太牛逼了，GitHub部署的网站都看不了了！

但是我自己在 github 上部署的站点能正常访问啊！

**Comment by Jiuyong** [comment]
真要被封了，也只能佩服那帮整天利用github搞反共宣传的NGO了。

**Comment by jiangzhonglian** [comment]
我最近找个服务器迁移迁移，别慌～

**Comment by jiangzhonglian** [comment]
各位兄弟， 应该恢复了吧？

**Comment by Jiuyong** [comment]
> 各位兄弟， 应该恢复了吧？

你操作的吗？现在好了，能正常访问了。是被墙了IP吗？还是你的域名没有实名制，所以不给你解析了啊？
