### ISSUE TITLE
雅可比矩阵定义，官方文档是对的，中文版本全部错误了（写成了转置后的矩阵了）。

### ISSUE THREAD

**Issue by Jiuyong** [apachecn/pytorch-doc-zh#533]
在 60min 快速教程的求导部分中，其中有个介绍求导推导的 雅可比矩阵 的定义。
发现中文文档中的公式中，雅可比举证 J=... 的定义的实际矩阵写成了转置后的了。
我特意去找了官方原文，官方原文是正确的。雅可比矩阵的准确定义可以参考相关百科。
我首先看的是 中文版1.4，但是发现 中文1.2 版本也存在，我猜想大概中文版从一开始就错误了。
不敢擅自改动，希望你们能核实下。

**Comment by jiangzhonglian** [comment]
可以提交一下PR，谢谢！ （请别把改错。我们鼓励修改。）

**Comment by Jiuyong** [comment]
行，我尝试着弄下~

**Comment by Jiuyong** [comment]
我先修改 1.4 版本，如果确认没有错误，我再将所有中文版都改动过来。

**Comment by Jiuyong** [comment]
只找到 1.0 版本有。

**Comment by Jiuyong** [comment]
看到了，其它的临时版本已经被删除了。这个问题应该可以关闭了。
