### ISSUE TITLE
关于 整体进度 v1.4（校对） #487  的疑问

### ISSUE THREAD

**Issue by GZYZG** [apachecn/pytorch-doc-zh#546]
我申领了 #487 中校对 [Autograd：自动求导](http://pytorch.apachecn.org/docs/1.4/blitz/autograd_tutorial.html)的任务，但是[Autograd：自动求导](http://pytorch.apachecn.org/docs/1.4/blitz/autograd_tutorial.html)的内容是Pytorch 1.8中对应的内容。

我的问题是：

我校对[Autograd：自动求导](http://pytorch.apachecn.org/docs/1.4/blitz/autograd_tutorial.html)时，是参照1.4还是1.8呢？

**Comment by jiangzhonglian** [comment]
我建议，如果你直接去改1.4的就行（它的版本迭代太频繁了，我们跟着他更新，是反应不过来的）
