### ISSUE TITLE
代码出错

### ISSUE THREAD

**Issue by LGAG** [apachecn/pytorch-doc-zh#565]
在PyTorch 中文官方教程 1.7文档《神经网络》章节, [链接为](https://pytorch.apachecn.org/#/docs/1.7/05)
定义网络中的卷积核应该是5x5而非3x3

**Comment by jiangzhonglian** [comment]
谢谢，已经修改： https://github.com/apachecn/pytorch-doc-zh/commit/8e273ac07f318b31fa6073d1d029967a8628d901
