### ISSUE TITLE
TorchScript 中的动态并行性 模块缺少相应代码

### ISSUE THREAD

**Issue by lugq1990** [apachecn/pytorch-doc-zh#568]
hi team，

感谢辛苦付出，让大家能够更好的学习！

在最新版的`TorchScript 中的动态并行性`章节，[旁注：可视化并行性](https://pytorch.apachecn.org/#/docs/1.7/48?id=%e6%97%81%e6%b3%a8%ef%bc%9a%e5%8f%af%e8%a7%86%e5%8c%96%e5%b9%b6%e8%a1%8c%e6%80%a7), 缺少部分代码，不然不会生成相应的文件，[英文位置](https://pytorch.org/tutorials/advanced/torch-script-parallelism.html#aside-visualizing-parallelism).

```python
with torch.autograd.profiler.profile() as prof:
    ens(x)
prof.export_chrome_trace('parallel.json')
```

对于上手应用的coder看到这里是不知道怎么才能使用chrome查看相应的线程对比。

希望添加以上代码。感谢！

**Comment by jiangzhonglian** [comment]
谢谢，已经修改：

https://github.com/apachecn/pytorch-doc-zh/commit/d4b5ac9bc9c3dc65afbb3c1552366dad7f214f89
