### ISSUE TITLE
翻译出错还是copy错了

### ISSUE THREAD

**Issue by Zhanghai-com** [apachecn/pytorch-doc-zh#572]
![微信图片_20220330104612](https://user-images.githubusercontent.com/60961135/160740856-4ff0f7c1-0c0f-4c71-a580-6efeba47f2d7.png)

**Comment by jiangzhonglian** [comment]
没找到你说的页面，麻烦发一下链接

**Comment by Zhanghai-com** [comment]
https://pytorch.apachecn.org/#/docs/1.7/20

**Comment by Zhanghai-com** [comment]
请教一下，在加载数据的时候， DataLoader这个的参数num_workers不为0的话报错： 
BrokenPipeError: [Errno 32] Broken pipe 
提示我需要这么解决：
File "E:\python\Anaconda3\envs\pytorch\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
我不清楚是不是我torch的版本问题，我直接默认了

**Comment by jiangzhonglian** [comment]
如果运行都出错了，建议查看英文官方代码，用最新稳定版本测试代码
