### ISSUE TITLE
v1.7 可选：数据并行  404NOT FOUND

### ISSUE THREAD

**Issue by butaixing** [apachecn/pytorch-doc-zh#574]
从 1.7
    >学习PyTorch
    >PyTorch深度学习：60分钟的突击
    >训练分类器
在多个 GPU 上进行训练
可选：数据并行
https://pytorch.apachecn.org/#/data_parallel_tutorial.html
404NOT FOUND

time: 2022/6/04 15:55:00

**Comment by jiangzhonglian** [comment]
谢谢好兄弟，已经修复了
