### ISSUE TITLE
翻译错误，@ 应该是矩阵乘法而不是点积

### ISSUE THREAD

**Issue by Suasy** [apachecn/pytorch-doc-zh#580]
https://pytorch.apachecn.org/#/docs/1.7/16?id=%e4%bb%8e%e9%9b%b6%e5%bc%80%e5%a7%8b%e7%9a%84%e7%a5%9e%e7%bb%8f%e7%bd%91%e7%bb%9c%ef%bc%88%e6%b2%a1%e6%9c%89torchnn%ef%bc%89

这一部分中

def model(xb):
    return log_softmax(xb @ weights + bias)

@ 翻译为了 “@代表点积运算”

原文是 “@ stands for the matrix multiplication operation”

这里翻译有问题，应该指的矩阵乘法，而点积是对应位置相乘

**Comment by jiangzhonglian** [comment]
谢谢！ 已经修改了
