### ISSUE TITLE
请问一下，我也用了docsify，然后借鉴了贵方的风格，但是我的搜索框不知道为什么不好用，无法搜索下层内容。

### ISSUE THREAD

**Issue by Chaaoo** [apachecn/pytorch-doc-zh#581]
请问一下，我也用了docsify，然后借鉴了贵方的风格，但是我的搜索框不知道为什么不好用，无法搜索下层内容。
我的站：https://cas.894732.xyz/

**Comment by jiangzhonglian** [comment]
MkDocs 可以了解一下，搜索支持更好

**Comment by Chaaoo** [comment]
好的，谢谢。刚才摸索出我的问题了，我的MD文档都是由html转换的，里面没有#一级标题导致。我会去了解一下MkDocs ，谢谢。
