### ISSUE TITLE
翻译勘误：tips

### ISSUE THREAD

**Issue by dundunkirk** [apachecn/pytorch-doc-zh#605]
在的PyTorch1.7中文文档的学习PyTorch的《torch.nn到底是什么？》中的从零开始的神经网络（没有torch.nn）里面将“tips”翻译为了“小费”，我个人觉得可能翻译为“提示”“小贴士”之类的会更为贴切一些。
[图片](https://s3.bmp.ovh/imgs/2023/07/03/3e1fb5b63bc2f7f3.png)

**Comment by jiangzhonglian** [comment]
OK OK，这就改！谢谢好兄弟
