### ISSUE TITLE
页面系统资源占用异常，导致标签页崩溃

### ISSUE THREAD

**Issue by ZeroCore-Zero** [apachecn/pytorch-doc-zh#672]
打开网站后，标签页占用内存与cpu迅速飙升，明显超出正常使用范畴
![image](https://github.com/apachecn/pytorch-doc-zh/assets/68436055/f85f7c8c-05e3-4586-995f-a5cf032f32a8)
图片中网址：https://pytorch.apachecn.org/

![image](https://github.com/apachecn/pytorch-doc-zh/assets/68436055/1e2ef7f2-6a07-4167-b7d9-ad91ce54bd09)
图片中网址：https://pytorch.apachecn.org/2.0/tutorials/beginner/basics/tensorqs_tutorial/

检测到即使是单个标签页，资源占用也在持续增长，且页面一经打开便不会被关闭，似乎是转入后台保活

内存占用随时间和站内跳转次数逐渐增长，最终导致页面OOM崩溃
![image](https://github.com/apachecn/pytorch-doc-zh/assets/68436055/e259ceda-c640-4b0e-957a-12e71330f7dc)

**复现方法**：任意打开网站界面，使用页面左侧导航栏单击任意链接跳转，等待OOM（逃
过程中可使用系统任务管理器或chrome的任务管理器（Shift+Esc）检测资源占用变化

**系统版本**：
Google Chrome | 123.0.6312.105 (Official Build) (64-bit) (cohort: M123 Rollout)
Revision | 399174dbe6eff0f59de9a6096129c0c827002b3a-refs/branch-heads/6312@{#761}
OS | Windows 11 Version 23H2 (Build 22631.3296)
JavaScript | V8 12.3.219.16
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
Command Line | "C:\Program Files\Google\Chrome\Application\chrome.exe" --flag-switches-begin --flag-switches-end --flag-switches-begin --flag-switches-end
Executable Path | C:\Program Files\Google\Chrome\Application\chrome.exe

**Comment by jiangzhonglian** [comment]
这个解决不了。这个用的框架，我这边只写md 文件。

**Comment by Glenn-Su** [comment]
禁用JS可以解决，但会无法正确显示公式和评论区
